README.md
=> Adding couple more new IDE's for force.com development

README.md
Hi,
- I noticed Illuminated Cloud, a new born IDE for Force.com and it is look nice 
- I used Workbench for a while and it also good
Then decide to suggest these two
Other things is removing trailing spaces ( from Contribution Guidelines )
> Make sure your text editor is set to remove trailing whitespace.
Sincerely,
Liratanak
=> Add Illuminated Cloud and Workbench

README.md
I re-pulled it, added ETL section and fixed conflicts.
Now it should look fine, check it please.
=> Add ETL Tools section

README.md
a ES6 Salesforce Formula parser
=> Add Formulon

README.md
Google custom search engines on the Salesforce domain can dramatically improve search experience and eliminate noise.
=> Add Salesforce custom search engines

README.md
A command line tool to access Salesforce using a low level CLI
=> Adding AdminBooster

README.md
Converting them from 15 to 18 characters
=> adding a tool to convert Salesforce IDs

README.md
Love this resource! Hope you find my contribution helpful
=> Shameless plug for my SOQL query tool

README.md
- Added info around Mavensmate support for VSCode
- Added Item for vscode code-completion plugin
=> Updated extensions in around vscode

README.md
@mailtoharshit Added a new library ESAPI to the Packages and libraries section.
=> Added ESAPI library under Packages and Libraries for Salesforce

README.md
R.apex(https://github.com/Click-to-Cloud/R.apex/) is a library to support functional programming in Apex. Besides, it provides utilities to manipulate Apex collections.
=> Add R.apex library under Packages and Libraries for Salesforce

README.md
This is a great repository. Observed few typos, have fixed them here.
=> Fixed Few Typos

README.md
Sweet.apex can transpile feature-rich Apex-like source files to Apex classes before you deploy them to your Org. In this way, you can apply fascinating features during your development.
=> add Sweet.apex to the developer utilities

README.md
This domain name is now a redirect to a fake flashplayer.
=> malware redirect link

README.md
Add Section for Podcasts and Good Day Sir Podcast
=> Add Section for Podcasts and Good Day Sir Podcast

README.md
Added reference to soql parser js.
Obtained latest branch and re-completed change as requested in #53
**Repo**: https://github.com/paustint/soql-parser-js
**Example**: https://paustint.github.io/soql-parser-js/
This library allows parsing/composing/formatting SOQL queries using Javascript which is very useful for certain types of tooling applications.
=> added soql-parser-js

README.md
Query.apex(https://github.com/Click-to-Cloud/Query.apex/) - Query.apex is a dynamic and flexible SOQL query builder.
=> Add Query.apex under Packages and Libraries for Salesforce

README.md
=> Mavensmate typos

README.md
Shutting the SOQooLio site down in 2020 and replacing it with a desktop application that's been renamed Adminite
=> SOQooLio > Adminite

README.md
For additional info, see:
- Github repository : https://github.com/exiahuang/xysfdx
- Direct link to VS Code extension page: https://marketplace.visualstudio.com/items?itemName=ExiaHuang.xysfdx
=> Add Salesforce VS Code extensions: xysfdx

README.md
@mailtoharshit Added a useful VS Code extension called Salesforce Snippets
=> Added a useful VS Code extension called Salesforce Snippets

README.md
[ApexTestKit](https://github.com/apexfarm/ApexTestKit). After 3 years of development, its APIs and features have become mature and stable. It can help create mock sObjects with one level child relationships, and multiple level parent relationships. Please check the readme for more features with it.
=> Add the ApexTestKit package
